environment:
  nodejs_version: "8"
  GH_TOKEN:
    secure: PFJDzS1/iJpNrWln7kDeZblyWRJTyNT04jFpcRE8U4AwJhEv88dJsivRaxLHKaCi

install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install

build: off

test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run standard
  - npm test -- --coverage
  - npm run dist

cache:
  - node_modules
