language: node_js
node_js:
  - "node"
install:
  - npm install
  # TODO: Pull client and socket as npm packages
  - cd src/masq/client
  - npm install
  - cd ../socket
  - npm install
  - cd ../..
script:
  - npm run standard
  - npm test -- --coverage
  # - npm run build
cache:
  directories:
    - "node_modules"
