language: node_js
node_js:
  - "node"
install:
  - git submodule update --init --recursive
  - npm install
script:
  - npm run standard
  - npm test -- --coverage
  - npm run build
cache:
  directories:
    - "node_modules"
